"""add summary json and memory videos

Revision ID: 26db1a5e7109
Revises: 2bc8284fe344
Create Date: 2026-04-27 10:22:23.373321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26db1a5e7109'
down_revision = '2bc8284fe344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_videos',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('storyboard_json', sa.JSON(), nullable=True),
    sa.Column('music_prompt', sa.Text(), nullable=True),
    sa.Column('music_url', sa.Text(), nullable=True),
    sa.Column('mubert_track_id', sa.String(length=255), nullable=True),
    sa.Column('creatomate_render_id', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['memorial_profiles.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['life_stories.story_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('video_id')
    )
    with op.batch_alter_table('memory_videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_videos_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_videos_creatomate_render_id'), ['creatomate_render_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_videos_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_videos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_videos_story_id'), ['story_id'], unique=False)

    with op.batch_alter_table('life_stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_json', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_life_stories_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_life_stories_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_life_stories_source_session_id'), ['source_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('life_stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_life_stories_source_session_id'))
        batch_op.drop_index(batch_op.f('ix_life_stories_profile_id'))
        batch_op.drop_index(batch_op.f('ix_life_stories_created_by'))
        batch_op.drop_column('summary_json')

    with op.batch_alter_table('memory_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_videos_story_id'))
        batch_op.drop_index(batch_op.f('ix_memory_videos_status'))
        batch_op.drop_index(batch_op.f('ix_memory_videos_profile_id'))
        batch_op.drop_index(batch_op.f('ix_memory_videos_creatomate_render_id'))
        batch_op.drop_index(batch_op.f('ix_memory_videos_created_by'))

    op.drop_table('memory_videos')
    # ### end Alembic commands ###
