"""add memories table

Revision ID: 29efc0546883
Revises: 30dbfa1a671f
Create Date: 2026-04-20 14:15:55.606917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29efc0546883'
down_revision = '30dbfa1a671f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['memorial_profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memories')
    # ### end Alembic commands ###
