"""add is_active to users

Revision ID: 30141ed2b86e
Revises: b0d04ab72dfa
Create Date: 2026-04-15 10:35:56.912176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30141ed2b86e'
down_revision = 'b0d04ab72dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
