"""Remove life story period location and happened date

Revision ID: 3d55053bf16b
Revises: 26db1a5e7109
Create Date: 2026-04-30 08:33:17.403622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d55053bf16b'
down_revision = '26db1a5e7109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('life_stories', schema=None) as batch_op:
        batch_op.drop_column('life_period')
        batch_op.drop_column('location')
        batch_op.drop_column('happened_at')

    with op.batch_alter_table('story_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_media_story_id'), ['story_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_media_story_id'))

    with op.batch_alter_table('life_stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('happened_at', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('life_period', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
