"""add chat analysis table

Revision ID: 7984b1114b5d
Revises: 20dfd980a148
Create Date: 2026-04-22 21:24:11.717503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7984b1114b5d'
down_revision = '20dfd980a148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_analysis',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('current_topic', sa.String(length=50), nullable=True),
    sa.Column('topic_complete', sa.Boolean(), nullable=False),
    sa.Column('show_topic_choices', sa.Boolean(), nullable=False),
    sa.Column('suggested_topics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['memorial_profiles.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    with op.batch_alter_table('chat_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_analysis_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_analysis_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_analysis_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_analysis_profile_id'))

    op.drop_table('chat_analysis')
    # ### end Alembic commands ###
