"""Add metadata fields to memories

Revision ID: c73c0e3b7bac
Revises: 3d55053bf16b
Create Date: 2026-04-30 13:53:01.733167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73c0e3b7bac'
down_revision = '3d55053bf16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('memory_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('topic', sa.String(length=50), nullable=True))
        batch_op.alter_column('memory_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_memories_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_topic'), ['topic'], unique=False)
        batch_op.drop_constraint(batch_op.f('memories_profile_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'memorial_profiles', ['profile_id'], ['profile_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('memories_profile_id_fkey'), 'memorial_profiles', ['profile_id'], ['profile_id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_memories_topic'))
        batch_op.drop_index(batch_op.f('ix_memories_profile_id'))
        batch_op.drop_index(batch_op.f('ix_memories_owner_id'))
        batch_op.alter_column('memory_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('topic')
        batch_op.drop_column('memory_date')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
